//
//  ItemBarCode_Md.m
//  RapidRMS
//
//  Created by Siya-mac5 on 19/10/15.
//  Copyright (c) 2015 Siya Infotech. All rights reserved.
//

#import "ItemBarCode_Md.h"
#import "Item.h"
#import "Item_Price_MD.h"


@implementation ItemBarCode_Md

@dynamic barCode;
@dynamic isBarcodeDeleted;
@dynamic isDefault;
@dynamic itemCode;
@dynamic packageType;
@dynamic srNo;
@dynamic updatedDate;
@dynamic isAutoGenerated;
@dynamic barcodeItem;
@dynamic barcodePrice_MD;

@end
