//
//  ItemBarCode_Md.h
//  RapidRMS
//
//  Created by Siya-mac5 on 19/10/15.
//  Copyright (c) 2015 Siya Infotech. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

@class Item, Item_Price_MD;

@interface ItemBarCode_Md : NSManagedObject

@property (nonatomic, retain) NSString * barCode;
@property (nonatomic, retain) NSNumber * isBarcodeDeleted;
@property (nonatomic, retain) NSNumber * isDefault;
@property (nonatomic, retain) NSNumber * itemCode;
@property (nonatomic, retain) NSString * packageType;
@property (nonatomic, retain) NSNumber * srNo;
@property (nonatomic, retain) NSDate * updatedDate;
@property (nonatomic, retain) NSNumber * isAutoGenerated;
@property (nonatomic, retain) Item *barcodeItem;
@property (nonatomic, retain) Item_Price_MD *barcodePrice_MD;

@end
