//
//  ItemBarCode_Md+Dictionary.m
//  RapidRMS
//
//  Created by Siya Infotech on 21/08/14.
//  Copyright (c) 2014 Siya Infotech. All rights reserved.
//

#import "ItemBarCode_Md+Dictionary.h"

@implementation ItemBarCode_Md (Dictionary)

-(NSDictionary *)itemBarcodeDictionary
{
    return nil;
}

//BarCode = LQ;
//IsDefault = 1;
//IsDeleted = 0;
//ItemId = 1;

-(void)updateItemBarcodeDictionary :(NSDictionary *)itemBarcodeDictionary
{
//    if ([[itemBarcodeDictionary valueForKey:@"BarCode"] isEqualToString:@"822720"])
//    {
//    }
    
    self.itemCode = @([[itemBarcodeDictionary valueForKey:@"ItemId"] integerValue]);
    
//    if ([[itemBarcodeDictionary valueForKey:@"PackageType"] length ] == 0)
//    {
//        self.packageType = @"Single Item";
//    }
//    else
//    {
        self.packageType = [itemBarcodeDictionary valueForKey:@"PackageType"];
//    }
   
    self.barCode = [itemBarcodeDictionary valueForKey:@"BarCode"];
    self.isDefault = @([[itemBarcodeDictionary valueForKey:@"IsDefault"] integerValue]);
    self.isBarcodeDeleted = @([[itemBarcodeDictionary valueForKey:@"IsDeleted"] integerValue]);
    self.srNo = @([[itemBarcodeDictionary valueForKey:@"SrNo"] integerValue]);
    self.isAutoGenerated = @([[itemBarcodeDictionary valueForKey:@"IsUPCAutoGenerated"] integerValue]);
}

@end